<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>MHZNet.DTO.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MHZNet.PO\MHZNet.PO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dto\Core\" />
    <Folder Include="Validators\" />
  </ItemGroup>

</Project>

