<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MHZNet.Common\MHZNet.Common.csproj" />
    <ProjectReference Include="..\MHZNet.IBusiness\MHZNet.IBusiness.csproj" />
  </ItemGroup>

</Project>

