<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>MHZNet.PO</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>MHZNet.PO.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MHZNet.Common\MHZNet.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
  </ItemGroup>

</Project>

