<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  
  
    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>MHZNet.Business.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MHZNet.Core\MHZNet.Core.csproj" />
    <ProjectReference Include="..\MHZNet.IBusiness\MHZNet.IBusiness.csproj" />
  </ItemGroup>

</Project>

